packages:
  - apps/react
  - apps/next
  - apps/express
  - apps/*
  - packages/*
allowBuilds:
  esbuild: true
  nx: true
  unrs-resolver: true

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

injectWorkspacePackages: true
